from __future__ import annotations

import os
from pathlib import Path
from unittest.mock import patch

from fastapi.testclient import TestClient

from stackwarden.contracts import ALLOWED_BUILD_STRATEGIES, SPEC_ID_PATTERN


def test_frontend_contract_constants_are_synced() -> None:
    repo = Path(__file__).resolve().parents[1]
    target = repo / "apps" / "web" / "src" / "api" / "contracts.generated.ts"
    expected = (
        "// AUTO-GENERATED by ops/scripts/generate_contract_types.py\n"
        "// Do not edit manually.\n\n"
        f"export const SPEC_ID_PATTERN = {SPEC_ID_PATTERN!r}\n"
        f"export const ALLOWED_BUILD_STRATEGIES = {list(ALLOWED_BUILD_STRATEGIES)!r} as const\n"
    )
    assert target.read_text(encoding="utf-8") == expected


def test_frontend_endpoint_shapes_match_backend_runtime(tmp_path) -> None:
    repo = Path(__file__).resolve().parents[1]
    endpoints = (repo / "apps" / "web" / "src" / "api" / "endpoints.ts").read_text(
        encoding="utf-8"
    )
    assert (
        "health: () => get<{ ok: boolean }>('/health')" in endpoints
        or 'health: () => get<{ ok: boolean }>("/health")' in endpoints
    )
    assert "cancel: (id: string) => post<{ canceled: boolean; job_id: string }>" in endpoints

    with patch.dict(
        os.environ,
        {"STACKWARDEN_DATA_DIR": str(tmp_path), "STACKWARDEN_WEB_DEV": "true"},
    ):
        from stackwarden.web.app import create_app
        from stackwarden.web.deps import get_job_manager
        from stackwarden.web.jobs.manager import JobManager
        from stackwarden.web.jobs.store import JobStore
        from stackwarden.web.settings import WebSettings

        manager = JobManager(store=JobStore(db_path=tmp_path / "catalog.sqlite3"))
        app = create_app(WebSettings(token=None, dev=True))
        app.dependency_overrides[get_job_manager] = lambda: manager
        client = TestClient(app)

        health = client.get("/api/health")
        assert health.status_code == 200
        assert health.json() == {"ok": True}

        job = manager.create_job(profile_id="p-sync", stack_id="s-sync", variants=None, flags={})
        cancel = client.post(f"/api/jobs/{job.job_id}/cancel")
        assert cancel.status_code == 200
        payload = cancel.json()
        assert set(payload.keys()) >= {"canceled", "job_id"}
