"""Generate frontend contract constants from backend source of truth."""

from __future__ import annotations

from pathlib import Path

from stackwarden.contracts import ALLOWED_BUILD_STRATEGIES, SPEC_ID_PATTERN


def main() -> None:
    root = Path(__file__).resolve().parents[2]
    target = root / "apps" / "web" / "src" / "api" / "contracts.generated.ts"
    content = (
        "// AUTO-GENERATED by ops/scripts/generate_contract_types.py\n"
        "// Do not edit manually.\n\n"
        f"export const SPEC_ID_PATTERN = {SPEC_ID_PATTERN!r}\n"
        f"export const ALLOWED_BUILD_STRATEGIES = {list(ALLOWED_BUILD_STRATEGIES)!r} as const\n"
    )
    target.write_text(content, encoding="utf-8")
    print(f"wrote {target}")


if __name__ == "__main__":
    main()
