// AUTO-GENERATED by tools/generate_contract_types.py
// Do not edit manually.

export const SPEC_ID_PATTERN = '^[a-z][a-z0-9_\\-]{2,63}$'
export const ALLOWED_BUILD_STRATEGIES = ['pull', 'overlay'] as const
